apiVersion: v1
kind: Pod
metadata:
    name: client-pod
    labels:
        component: web
spec:
    containers:
        - name: client
          image: samnoh/multi-client
          ports:
              - containerPort: 3000 # expose port 3000
